/**
 * The engine's shared puzzle vocabulary: geometry, colors, config descriptions
 * and the change notifications the engine emits.
 *
 * Every name here belongs to a contract the **engine** states and a game
 * implements — `Color` is what `Game.colors()` returns, `Rect`/`Point`/`Size`
 * are the drawing API's coordinate records. The app is a consumer. Several are
 * still upstream's C structures seen through a JS lens (a `Color` is an RGB
 * triple in 0..1, not a CSS string), which is why they read the way they do.
 *
 * These declarations used to be *re-exported from the Emscripten-generated*
 * `src/assets/puzzles/emcc-runtime.d.ts` — so the native TypeScript engine's
 * type vocabulary was, literally, emitted by `emcc --emit-tsd` from
 * `webapp.cpp`, which made a generated file in a gitignored assets directory
 * the root of the type graph for 200-odd files. `retire-c-engine` hand-authored
 * them in the app layer instead, at `src/puzzle/types.ts`, preserving every
 * shape exactly so that not one importer had to change — the right call when
 * the goal was proving nothing else had moved.
 *
 * That left the engine importing its own vocabulary from the shell, and left
 * the layering test unable to say so. `retire-native-directory` moved the file
 * down here, which is what lets that test assert the real invariant: the engine
 * and the games import nothing above them.
 */

/** An RGB triple, each component in 0..1 — the puzzle drawing API's color
 * representation, as fed to and returned by a game's `colors()`. */
export type Color = [number, number, number];

export type Point = {
  x: number;
  y: number;
};

export type Size = {
  w: number;
  h: number;
};

export type Rect = {
  x: number;
  y: number;
  w: number;
  h: number;
};

/** A label for an on-screen key the game wants offered, and the button code
 * pressing it should deliver. */
export type KeyLabel = {
  label: string;
  button: number;
};

/** One entry in the game-type preset menu; `submenu` makes it a nested group
 * rather than a selectable preset. */
export type PresetMenuEntry = {
  title: string;
  params: string;
  submenu?: PresetMenuEntry[] | undefined;
};

export type DrawTextOptions = {
  align: "left" | "center" | "right";
  baseline: "alphabetic" | "mathematical";
  fontType: "fixed" | "variable";
  size: number;
};

export type NotifyGameIdChange = {
  type: "game-id-change";
  currentGameId: string;
  randomSeed?: string | undefined;
};

export type NotifyGameStateChange = {
  type: "game-state-change";
  status: "ongoing" | "solved" | "solved-with-help" | "lost";
  currentMove: number;
  totalMoves: number;
  canUndo: boolean;
  canRedo: boolean;
};

export type NotifyParamsChange = {
  type: "params-change";
  params: string;
};

export interface NotifyStatusBarChange {
  type: "status-bar-change";
  statusBarText: string;
  activeHintExplanation?: string;
}

export type PuzzleId = string;
export type EncodedParams = string;

/** One field in a config dialog (custom game params, or preferences). */
export type ConfigItem =
  | { type: "string"; name: string }
  | { type: "boolean"; name: string }
  | { type: "choices"; name: string; choicenames: string[] };

/** A whole config dialog: a title and its fields, keyed by field id. */
export type ConfigDescription = {
  title: string;
  items: { [id: string]: ConfigItem };
};

/** The values of a `ConfigDescription`'s fields, keyed by the same ids.
 * A `choices` field's value is its zero-based index. */
export type ConfigValues = Record<string, string | boolean | number>;

export type ChangeNotification =
  | NotifyGameIdChange
  | NotifyGameStateChange
  | NotifyParamsChange
  | NotifyStatusBarChange;

export type GameStatus = NotifyGameStateChange["status"];

export enum PuzzleButton {
  LEFT_BUTTON = 0x0200,
  MIDDLE_BUTTON,
  RIGHT_BUTTON,
  LEFT_DRAG,
  MIDDLE_DRAG,
  RIGHT_DRAG,
  LEFT_RELEASE,
  MIDDLE_RELEASE,
  RIGHT_RELEASE,
  CURSOR_UP,
  CURSOR_DOWN,
  CURSOR_LEFT,
  CURSOR_RIGHT,
  CURSOR_SELECT,
  CURSOR_SELECT2,
  /* UI_* are special keystrokes generated by front ends in response
   * to menu actions, never passed to back ends */
  UI_LOWER_BOUND,
  UI_QUIT,
  UI_NEWGAME,
  UI_SOLVE,
  UI_UNDO,
  UI_REDO,
  UI_UPPER_BOUND,

  /* made smaller because of 'limited range of datatype' errors. */
  MOD_STYLUS = 0x0800,
  MOD_CTRL = 0x1000,
  MOD_SHFT = 0x2000,
  MOD_NUM_KEYPAD = 0x4000,
  MOD_MASK = 0x7800 /* mask for all modifiers */,
}

/**
 * What the app learns about a game once, at construction, and never asks again.
 *
 * Every field is produced by `Midend.getStaticProperties` and relayed — under
 * the same name — into a `Puzzle` field, so the chain is easy to extend and its
 * far end is easy to forget: **two of the original nine fields turned out to
 * have no reader at all**, `canConfigure` (which the midend answered with a
 * literal `true`) and `displayName` (which `Puzzle` overrode from the catalog on
 * every path). `contract-surface.test.ts` sweeps this interface for the same
 * reason it sweeps `Game`.
 */
export interface PuzzleStaticAttributes {
  // A `canConfigure` used to sit here, gating the type menu's "Custom type…"
  // entry — and the midend answered it with a hard-coded `true`, so the gate
  // never closed. Every game declares a `paramConfig`, which
  // `custom-params.test.ts` now asserts, so the entry is unconditional; a
  // future preset-only game reopens the question with that test as the prompt
  // (`audit-vestigial-contract-surface`).
  canSolve: boolean;
  canHint: boolean;
  /** The game can check the board for mistakes (the `findMistakes` hook). */
  canFindMistakes: boolean;
  /** The game supports "fill all pencil marks" (upstream's `M` key). Gates
   * the toolbar mark-all button. */
  canMarkAll: boolean;
  /** The game offers a reference aid (the `reference` hook) — a checklist
   * of its fixed inventory with found status. Gates the toolbar reference
   * button. */
  hasReference: boolean;
  // TODO: canFormatAsTextEver: boolean;
  /** The game has no meaning for the secondary button, so the view must not
   * synthesize one from a long press or a two-finger tap — see
   * `Game.ignoresSecondaryButton`. */
  ignoresSecondaryButton: boolean;
  isTimed: boolean;
  wantsStatusbar: boolean;
}

/** One entry in a game's reference aid: a piece from the puzzle's fixed
 * inventory with the player's found status. Plain data (crosses the Comlink
 * worker boundary). `key` is a stable id the panel echoes back to
 * `selectReference`; `label` is the text/accessible rendering; `pips` is
 * optional face-value data for a domino-style pip render; `status` is derived
 * purely from the player's own placements. */
export interface ReferenceItem {
  key: string;
  label: string;
  pips?: readonly number[];
  status: "outstanding" | "placed" | "conflict";
}

/** A game's reference-aid model: the full inventory checklist plus the
 * currently spotlighted key. `columns` is an optional layout hint. */
export interface ReferenceModel {
  items: ReferenceItem[];
  selected: string | null;
  columns?: number;
}

/**
 * Drawing font selection
 */
export interface FontInfo {
  fontFamily: string;
  fontWeight: string;
  fontStyle: string;
}
