/**
 * The game catalog: every puzzle the app serves, with the metadata the home
 * screen, the puzzle pages and the help system render.
 *
 * This is a **committed source**, and deliberately so. Until `retire-c-engine`
 * it was `src/assets/puzzles/catalog.json`, generated by CMake from the
 * `puzzle()` macro calls in `puzzles/CMakeLists.txt` — so the app's game list
 * was a build output of the Emscripten toolchain, written into a gitignored
 * directory, and `vite.config.ts` imported it at config-load time. A clean
 * checkout could not even parse the vite config until the wasm build had run.
 *
 * The metadata below was migrated out of those CMake files (it existed nowhere
 * else) and verified against the last generated catalog: 57 games, zero field
 * differences, by an independent parse of the `puzzle()` calls.
 *
 * Adding a game means adding it here AND registering it in
 * `src/native/games/index.ts`; `catalog-data.test.ts` and
 * `ts-ported-ids.test.ts` hold the two lists to each other.
 */

export interface PuzzleData {
  name: string;
  description: string;
  objective: string;
  collection: "original" | "unreleased";
  /** An upstream *unfinished* puzzle someone opted into building. Nothing in
   * the shipped catalog sets this today; the home screen still honours it. */
  unfinished?: boolean;
}

export const puzzleCatalog = {
  abcd: {
    name: "ABCD",
    description: "Letter placement puzzle",
    objective:
      "Place letters according to the numbers. Identical letters cannot touch.",
    collection: "unreleased",
  },
  ascent: {
    name: "Ascent",
    description: "Path-finding puzzle",
    objective: "Place each number once to create a path.",
    collection: "unreleased",
  },
  blackbox: {
    name: "Black Box",
    description: "Ball-finding puzzle",
    objective: "Find the hidden balls in the box by bouncing laser beams off them.",
    collection: "original",
  },
  boats: {
    name: "Boats",
    description: "Boat-placing puzzle",
    objective: "Find the fleet in the grid.",
    collection: "unreleased",
  },
  bricks: {
    name: "Bricks",
    description: "Hexagonal shading puzzle",
    objective:
      "Shade several cells in the hexagonal grid while making sure each cell has another shaded cell below it.",
    collection: "unreleased",
  },
  bridges: {
    name: "Bridges",
    description: "Bridge-placing puzzle",
    objective: "Connect all the islands with a network of bridges.",
    collection: "original",
  },
  clusters: {
    name: "Clusters",
    description: "Red and blue grid puzzle",
    objective: "Fill in the grid with red and blue clusters, with all dead ends given.",
    collection: "unreleased",
  },
  crossing: {
    name: "Crossing",
    description: "Number crossword puzzle",
    objective: "Place each number from the list into the crossword.",
    collection: "unreleased",
  },
  cube: {
    name: "Cube",
    description: "Rolling cube puzzle",
    objective: "Pick up all the blue squares by rolling the cube over them.",
    collection: "original",
  },
  dominosa: {
    name: "Dominosa",
    description: "Domino tiling puzzle",
    objective: "Tile the rectangle with a full set of dominoes.",
    collection: "original",
  },
  fifteen: {
    name: "Fifteen",
    description: "Sliding block puzzle",
    objective: "Slide the tiles around to arrange them into order.",
    collection: "original",
  },
  filling: {
    name: "Filling",
    description: "Polyomino puzzle",
    objective: "Mark every square with the area of its containing region.",
    collection: "original",
  },
  flip: {
    name: "Flip",
    description: "Tile inversion puzzle",
    objective: "Flip groups of squares to light them all up at once.",
    collection: "original",
  },
  flood: {
    name: "Flood",
    description: "Flood-filling puzzle",
    objective: "Turn the grid the same colour in as few flood fills as possible.",
    collection: "original",
  },
  galaxies: {
    name: "Galaxies",
    description: "Symmetric polyomino puzzle",
    objective:
      "Divide the grid into rotationally symmetric regions each centred on a dot.",
    collection: "original",
  },
  group: {
    name: "Group",
    description: "Group theory puzzle",
    objective: "Complete the unfinished Cayley table of a group.",
    collection: "original",
  },
  guess: {
    name: "Guess",
    description: "Combination-guessing puzzle",
    objective: "Guess the hidden combination of colours.",
    collection: "original",
  },
  inertia: {
    name: "Inertia",
    description: "Gem-collecting puzzle",
    objective: "Collect all the gems without running into any of the mines.",
    collection: "original",
  },
  keen: {
    name: "Keen",
    description: "Arithmetic Latin square puzzle",
    objective: "Complete the latin square in accordance with the arithmetic clues.",
    collection: "original",
  },
  lightup: {
    name: "Light Up",
    description: "Light-bulb placing puzzle",
    objective: "Place bulbs to light up all the squares.",
    collection: "original",
  },
  loopy: {
    name: "Loopy",
    description: "Loop-drawing puzzle",
    objective: "Draw a single closed loop, given clues about number of adjacent edges.",
    collection: "original",
  },
  magnets: {
    name: "Magnets",
    description: "Magnet-placing puzzle",
    objective: "Place magnets to satisfy the clues and avoid like poles touching.",
    collection: "original",
  },
  map: {
    name: "Map",
    description: "Map-colouring puzzle",
    objective: "Colour the map so that adjacent regions are never the same colour.",
    collection: "original",
  },
  mathrax: {
    name: "Mathrax",
    description: "Latin square puzzle",
    objective: "Place each number according to the arithmetic clues.",
    collection: "unreleased",
  },
  mines: {
    name: "Mines",
    description: "Mine-finding puzzle",
    objective: "Find all the mines without treading on any of them.",
    collection: "original",
  },
  mosaic: {
    name: "Mosaic",
    description: "Grid-filling puzzle",
    objective: "Fill in the grid given clues about number of nearby black squares.",
    collection: "original",
  },
  net: {
    name: "Net",
    description: "Network jigsaw puzzle",
    objective: "Rotate each tile to reassemble the network.",
    collection: "original",
  },
  netslide: {
    name: "Netslide",
    description: "Toroidal sliding network puzzle",
    objective: "Slide a row at a time to reassemble the network.",
    collection: "original",
  },
  palisade: {
    name: "Palisade",
    description: "Grid-division puzzle",
    objective: "Divide the grid into equal-sized areas in accordance with the clues.",
    collection: "original",
  },
  pattern: {
    name: "Pattern",
    description: "Pattern puzzle",
    objective:
      "Fill in the pattern in the grid, given only the lengths of runs of black squares.",
    collection: "original",
  },
  pearl: {
    name: "Pearl",
    description: "Loop-drawing puzzle",
    objective:
      "Draw a single closed loop, given clues about corner and straight squares.",
    collection: "original",
  },
  pegs: {
    name: "Pegs",
    description: "Peg solitaire puzzle",
    objective: "Jump pegs over each other to remove all but one.",
    collection: "original",
  },
  range: {
    name: "Range",
    description: "Visible-distance puzzle",
    objective:
      "Place black squares to limit the visible distance from each numbered cell.",
    collection: "original",
  },
  rect: {
    name: "Rectangles",
    description: "Rectangles puzzle",
    objective: "Divide the grid into rectangles with areas equal to the numbers.",
    collection: "original",
  },
  rome: {
    name: "Rome",
    description: "Arrow-placing puzzle",
    objective: "Fill the grid with arrows leading to a goal.",
    collection: "unreleased",
  },
  salad: {
    name: "Salad",
    description: "Pseudo-Latin square puzzle",
    objective:
      "Place each character once in every row and column. Some squares remain empty.",
    collection: "unreleased",
  },
  samegame: {
    name: "Same Game",
    description: "Block-clearing puzzle",
    objective: "Clear the grid by removing touching groups of the same colour squares.",
    collection: "original",
  },
  seismic: {
    name: "Seismic",
    description: "Number placement puzzle",
    objective:
      "Place numbers in each area, keeping enough distance between equal numbers.",
    collection: "unreleased",
  },
  separate: {
    name: "Separate",
    description: "Rectangle-dividing puzzle",
    objective: "Partition the grid into regions containing one of each letter.",
    collection: "original",
  },
  signpost: {
    name: "Signpost",
    description: "Square-connecting puzzle",
    objective: "Connect the squares into a path following the arrows.",
    collection: "original",
  },
  singles: {
    name: "Singles",
    description: "Number-removing puzzle",
    objective: "Black out the right set of duplicate numbers.",
    collection: "original",
  },
  sixteen: {
    name: "Sixteen",
    description: "Toroidal sliding block puzzle",
    objective: "Slide a row at a time to arrange the tiles into order.",
    collection: "original",
  },
  slant: {
    name: "Slant",
    description: "Maze-drawing puzzle",
    objective: "Draw a maze of slanting lines that matches the clues.",
    collection: "original",
  },
  slide: {
    name: "Slide",
    description: "Sliding block puzzle",
    objective: "Slide the blocks to let the key block out.",
    collection: "original",
  },
  sokoban: {
    name: "Sokoban",
    description: "Barrel-pushing puzzle",
    objective: "Push all the barrels into the target squares.",
    collection: "original",
  },
  solo: {
    name: "Solo",
    description: "Number placement puzzle",
    objective:
      "Fill in the grid so that each row, column and square block contains one of every digit.",
    collection: "original",
  },
  spokes: {
    name: "Spokes",
    description: "Wheel-connecting puzzle",
    objective: "Connect all hubs using horizontal, vertical and diagonal lines.",
    collection: "unreleased",
  },
  sticks: {
    name: "Sticks",
    description: "Line-drawing puzzle",
    objective: "Fill in the grid with horizontal and vertical line segments.",
    collection: "unreleased",
  },
  subsets: {
    name: "Subsets",
    description: "Set-defining puzzle",
    objective: "Place each set once, in accordance with the subset clues.",
    collection: "unreleased",
  },
  tents: {
    name: "Tents",
    description: "Tent-placing puzzle",
    objective: "Place a tent next to each tree.",
    collection: "original",
  },
  towers: {
    name: "Towers",
    description: "Tower-placing Latin square puzzle",
    objective: "Complete the latin square of towers in accordance with the clues.",
    collection: "original",
  },
  tracks: {
    name: "Tracks",
    description: "Path-finding railway track puzzle",
    objective: "Fill in the railway track according to the clues.",
    collection: "original",
  },
  twiddle: {
    name: "Twiddle",
    description: "Rotational sliding block puzzle",
    objective: "Rotate the tiles around themselves to arrange them into order.",
    collection: "original",
  },
  undead: {
    name: "Undead",
    description: "Monster-placing puzzle",
    objective:
      "Place ghosts, vampires and zombies so that the right numbers of them can be seen in mirrors.",
    collection: "original",
  },
  unequal: {
    name: "Unequal",
    description: "Latin square puzzle",
    objective: "Complete the latin square in accordance with the > signs.",
    collection: "original",
  },
  unruly: {
    name: "Unruly",
    description: "Black and white grid puzzle",
    objective: "Fill in the black and white grid to avoid runs of three.",
    collection: "original",
  },
  untangle: {
    name: "Untangle",
    description: "Planar graph layout puzzle",
    objective: "Reposition the points so that the lines do not cross.",
    collection: "original",
  },
} as const satisfies Record<string, PuzzleData>;

/** Catalog ids, sorted — the display order the home screen and menus use. */
export const puzzleIds: readonly string[] = Object.keys(puzzleCatalog);
