/**
 * The app's shared puzzle vocabulary: geometry, colours, config descriptions
 * and the change notifications the engine emits.
 *
 * These declarations used to be *re-exported from the Emscripten-generated*
 * `src/assets/puzzles/emcc-runtime.d.ts` — so the native TypeScript engine's
 * type vocabulary was, literally, emitted by `emcc --emit-tsd` from
 * `webapp.cpp`. 202 files import from this module, which made a generated file
 * in a gitignored assets directory the root of the type graph; nothing noticed
 * because `tsc` only ever ran on trees where `build:wasm` had already been run.
 *
 * `retire-c-engine` hand-authored them here instead, preserving every shape
 * exactly so that not one importer had to change. Several are still upstream's
 * C structures seen through a JS lens (`Colour` is an RGB triple in 0..1, not a
 * CSS string; `Rect`/`Point`/`Size` are the drawing API's coordinate records),
 * which is why they read the way they do.
 */

/** An RGB triple, each component in 0..1 — the puzzle drawing API's colour
 * representation, as fed to and returned by a game's `colours()`. */
export type Colour = [number, number, number];

export type Point = {
  x: number;
  y: number;
};

export type Size = {
  w: number;
  h: number;
};

export type Rect = {
  x: number;
  y: number;
  w: number;
  h: number;
};

/** A label for an on-screen key the game wants offered, and the button code
 * pressing it should deliver. */
export type KeyLabel = {
  label: string;
  button: number;
};

/** One entry in the game-type preset menu; `submenu` makes it a nested group
 * rather than a selectable preset. */
export type PresetMenuEntry = {
  title: string;
  params: string;
  submenu?: PresetMenuEntry[] | undefined;
};

export type DrawTextOptions = {
  align: "left" | "center" | "right";
  baseline: "alphabetic" | "mathematical";
  fontType: "fixed" | "variable";
  size: number;
};

export type NotifyGameIdChange = {
  type: "game-id-change";
  currentGameId: string;
  randomSeed?: string | undefined;
};

export type NotifyGameStateChange = {
  type: "game-state-change";
  status: "ongoing" | "solved" | "solved-with-help" | "lost";
  currentMove: number;
  totalMoves: number;
  canUndo: boolean;
  canRedo: boolean;
};

export type NotifyParamsChange = {
  type: "params-change";
  params: string;
};

export interface NotifyStatusBarChange {
  type: "status-bar-change";
  statusBarText: string;
  activeHintExplanation?: string;
}

export type PuzzleId = string;
export type EncodedParams = string;

/** One field in a config dialog (custom game params, or preferences). */
export type ConfigItem =
  | { type: "string"; name: string }
  | { type: "boolean"; name: string }
  | { type: "choices"; name: string; choicenames: string[] };

/** A whole config dialog: a title and its fields, keyed by field id. */
export type ConfigDescription = {
  title: string;
  items: { [id: string]: ConfigItem };
};

/** The values of a `ConfigDescription`'s fields, keyed by the same ids.
 * A `choices` field's value is its zero-based index. */
export type ConfigValues = Record<string, string | boolean | number>;

export type ChangeNotification =
  | NotifyGameIdChange
  | NotifyGameStateChange
  | NotifyParamsChange
  | NotifyStatusBarChange;

export type GameStatus = NotifyGameStateChange["status"];

export enum PuzzleButton {
  LEFT_BUTTON = 0x0200,
  MIDDLE_BUTTON,
  RIGHT_BUTTON,
  LEFT_DRAG,
  MIDDLE_DRAG,
  RIGHT_DRAG,
  LEFT_RELEASE,
  MIDDLE_RELEASE,
  RIGHT_RELEASE,
  CURSOR_UP,
  CURSOR_DOWN,
  CURSOR_LEFT,
  CURSOR_RIGHT,
  CURSOR_SELECT,
  CURSOR_SELECT2,
  /* UI_* are special keystrokes generated by front ends in response
   * to menu actions, never passed to back ends */
  UI_LOWER_BOUND,
  UI_QUIT,
  UI_NEWGAME,
  UI_SOLVE,
  UI_UNDO,
  UI_REDO,
  UI_UPPER_BOUND,

  /* made smaller because of 'limited range of datatype' errors. */
  MOD_STYLUS = 0x0800,
  MOD_CTRL = 0x1000,
  MOD_SHFT = 0x2000,
  MOD_NUM_KEYPAD = 0x4000,
  MOD_MASK = 0x7800 /* mask for all modifiers */,
}

export interface PuzzleStaticAttributes {
  displayName: string;
  canConfigure: boolean;
  canSolve: boolean;
  canHint: boolean;
  /** The game can check the board for mistakes (the `findMistakes` hook). */
  canFindMistakes: boolean;
  /** The game supports "fill all pencil marks" (upstream's `M` key). Gates
   * the toolbar mark-all button. */
  canMarkAll: boolean;
  /** The game offers a reference aid (the `reference` hook) — a checklist
   * of its fixed inventory with found status. Gates the toolbar reference
   * button. */
  hasReference: boolean;
  // TODO: canFormatAsTextEver: boolean;
  needsRightButton: boolean;
  isTimed: boolean;
  wantsStatusbar: boolean;
}

/** One entry in a game's reference aid: a piece from the puzzle's fixed
 * inventory with the player's found status. Plain data (crosses the Comlink
 * worker boundary). `key` is a stable id the panel echoes back to
 * `selectReference`; `label` is the text/accessible rendering; `pips` is
 * optional face-value data for a domino-style pip render; `status` is derived
 * purely from the player's own placements. */
export interface ReferenceItem {
  key: string;
  label: string;
  pips?: readonly number[];
  status: "outstanding" | "placed" | "conflict";
}

/** A game's reference-aid model: the full inventory checklist plus the
 * currently spotlighted key. `columns` is an optional layout hint. */
export interface ReferenceModel {
  items: ReferenceItem[];
  selected: string | null;
  columns?: number;
}

/**
 * Drawing font selection
 */
export interface FontInfo {
  fontFamily: string;
  fontWeight: string;
  fontStyle: string;
}
