/**
 * Additional typing for the Emscripten generated code.
 */

import type {
  ClassHandle,
  DrawingWrapper,
  Frontend,
  MainModule,
  NotifyGameIdChange,
  NotifyGameStateChange,
  NotifyParamsChange,
  Point,
  Size,
} from "../assets/puzzles/emcc-runtime";

// (Re-export generated types so other code doesn't need to dig into assets.)
export type {
  Colour,
  Drawing,
  DrawingWrapper,
  DrawTextOptions,
  Frontend,
  FrontendConstructorArgs,
  KeyLabel,
  NotifyGameIdChange,
  NotifyGameStateChange,
  NotifyParamsChange,
  Point,
  PresetMenuEntry,
  Rect,
  Size,
} from "../assets/puzzles/emcc-runtime";

export interface NotifyStatusBarChange {
  type: "status-bar-change";
  statusBarText: string;
  activeHintExplanation?: string;
}

export type PuzzleId = string;
export type EncodedParams = string;

export type ConfigDescription = ReturnType<Frontend["getPreferencesConfig"]>;
export type ConfigItem = ReturnType<Frontend["getPreferencesConfig"]>["items"]["any"];
export type ConfigValues = ReturnType<Frontend["getPreferences"]>;

export type ChangeNotification =
  | NotifyGameIdChange
  | NotifyGameStateChange
  | NotifyParamsChange
  | NotifyStatusBarChange;

export type GameStatus = NotifyGameStateChange["status"];

export enum PuzzleButton {
  LEFT_BUTTON = 0x0200,
  MIDDLE_BUTTON,
  RIGHT_BUTTON,
  LEFT_DRAG,
  MIDDLE_DRAG,
  RIGHT_DRAG,
  LEFT_RELEASE,
  MIDDLE_RELEASE,
  RIGHT_RELEASE,
  CURSOR_UP,
  CURSOR_DOWN,
  CURSOR_LEFT,
  CURSOR_RIGHT,
  CURSOR_SELECT,
  CURSOR_SELECT2,
  /* UI_* are special keystrokes generated by front ends in response
   * to menu actions, never passed to back ends */
  UI_LOWER_BOUND,
  UI_QUIT,
  UI_NEWGAME,
  UI_SOLVE,
  UI_UNDO,
  UI_REDO,
  UI_UPPER_BOUND,

  /* made smaller because of 'limited range of datatype' errors. */
  MOD_STYLUS = 0x0800,
  MOD_CTRL = 0x1000,
  MOD_SHFT = 0x2000,
  MOD_NUM_KEYPAD = 0x4000,
  MOD_MASK = 0x7800 /* mask for all modifiers */,
}

/** Which engine implementation backs this puzzle instance. Surfaced
 * for the dev-mode "TS" / "C" badge in the puzzle header, so an owner
 * doing parity testing can see at a glance which path they're playing
 * on. Fixed at construction time per puzzle. */
export type PuzzleEngineType = "ts" | "wasm";

export interface PuzzleStaticAttributes {
  displayName: string;
  canConfigure: boolean;
  canSolve: boolean;
  canHint: boolean;
  /** The game can check the board for mistakes (the TS `findMistakes`
   * hook). False for C/WASM games. */
  canFindMistakes: boolean;
  /** The game supports "fill all pencil marks" (upstream's `M` key). Gates
   * the toolbar mark-all button. False for C/WASM games. */
  canMarkAll: boolean;
  /** The game offers a reference aid (the TS `reference` hook) — a checklist
   * of its fixed inventory with found status. Gates the toolbar reference
   * button. False for C/WASM games. */
  hasReference: boolean;
  // TODO: canFormatAsTextEver: boolean;
  needsRightButton: boolean;
  isTimed: boolean;
  wantsStatusbar: boolean;
  engineType: PuzzleEngineType;
}

/** One entry in a game's reference aid: a piece from the puzzle's fixed
 * inventory with the player's found status. Plain data (crosses the Comlink
 * worker boundary). `key` is a stable id the panel echoes back to
 * `selectReference`; `label` is the text/accessible rendering; `pips` is
 * optional face-value data for a domino-style pip render; `status` is derived
 * purely from the player's own placements. */
export interface ReferenceItem {
  key: string;
  label: string;
  pips?: readonly number[];
  status: "outstanding" | "placed" | "conflict";
}

/** A game's reference-aid model: the full inventory checklist plus the
 * currently spotlighted key. `columns` is an optional layout hint. */
export interface ReferenceModel {
  items: ReferenceItem[];
  selected: string | null;
  columns?: number;
}

/**
 * Required JS-side implementation for Drawing API
 */
export interface DrawingImpl<Blitter = unknown>
  extends Omit<DrawingWrapper, keyof ClassHandle | "notifyOnDestruction">,
    Partial<Pick<DrawingWrapper, "notifyOnDestruction">> {
  // Redeclare blitter methods to improve typing
  blitterNew(size: Size): Blitter;
  blitterFree(blitter: Blitter): void;
  blitterSave(blitter: Blitter, origin: Point): void;
  blitterLoad(blitter: Blitter, origin?: Point): void;
}

/**
 * The Emscripten generated module object
 */
export interface PuzzleModule extends MainModule {
  // Replace `any` args for Drawing.implement()
  Drawing: {
    implement(drawing: DrawingImpl): DrawingWrapper;
    extend: MainModule["Drawing"]["extend"];
  };
}

/**
 * Drawing font selection
 */
export interface FontInfo {
  fontFamily: string;
  fontWeight: string;
  fontStyle: string;
}
