/**
 * Render metrics/<date>/summary.md from the raw tool output in that directory.
 *
 * The summary is what a later round diffs against, so it must be honest about
 * what it could not measure. Two rules it exists to enforce:
 *
 *  - Biome's cognitive-complexity counter SATURATES AT 255 (verified by probing
 *    a synthetic function of true complexity 300, which reports 255). A
 *    saturating instrument reports "no regression" precisely once you are past
 *    its ceiling, so saturated readings are printed as ">=255" and excluded from
 *    the maximum. Never record 255 as a measured maximum.
 *  - Cross-game duplication is reported separately from the headline percentage.
 *    2% tree-wide says little; "466 lines between two games that are the same
 *    game" is the actionable number.
 *
 * Usage: node scripts/metrics-summary.mjs metrics/<date>
 */
import fs from "node:fs";
import path from "node:path";

const dir = process.argv[2];
const read = (f) => {
  try {
    return fs.readFileSync(path.join(dir, f), "utf8");
  } catch {
    return "";
  }
};
const SATURATION = 255;

const out = [];
out.push(`# Metrics — ${path.basename(dir)}`);
out.push("");
out.push("Generated by `npm run metrics`. See `scripts/metrics.sh` for what each");
out.push("number does and does not mean.");
out.push("");

// --- duplication ------------------------------------------------------------
let jscpd = null;
try {
  jscpd = JSON.parse(read(path.join("jscpd", "jscpd-report.json")));
} catch {
  /* absent */
}
out.push("## Duplication (jscpd, min-tokens 60)");
out.push("");
if (jscpd) {
  const ts = jscpd.statistics?.formats?.typescript?.total;
  const dup = (jscpd.duplicates ?? []).filter((d) => d.format === "typescript");
  // Indexed off the match, not off a hardcoded depth: `retire-native-directory`
  // hoisted this tree from src/native/games/<id> to src/games/<id>, and a
  // literal `split("/")[3]` would have gone on returning a *filename* as the
  // game id, silently mis-scoring cross-game duplication rather than failing.
  const gameOf = (p) => /^src\/games\/([^/]+)\//.exec(p)?.[1] ?? null;
  const crossGame = dup.filter((d) => {
    const a = gameOf(d.firstFile.name);
    const b = gameOf(d.secondFile.name);
    return a && b && a !== b;
  });
  const byPair = new Map();
  for (const d of crossGame) {
    const key = [gameOf(d.firstFile.name), gameOf(d.secondFile.name)]
      .sort()
      .join(" ↔ ");
    byPair.set(key, (byPair.get(key) ?? 0) + d.lines);
  }
  if (ts) {
    out.push(`- lines: **${ts.percentage}%** (${ts.duplicatedLines} of ${ts.lines})`);
    out.push(`- tokens: **${ts.percentageTokens}%**`);
  }
  out.push(`- clones: ${dup.length}`);
  out.push(
    `- **cross-game clone lines: ${crossGame.reduce((s, d) => s + d.lines, 0)}** ` +
      `across ${crossGame.length} blocks`,
  );
  out.push("");
  out.push("Worst cross-game pairs (the actionable part — same game, two copies):");
  out.push("");
  for (const [pair, lines] of [...byPair.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8)) {
    out.push(`- ${pair} — ${lines} lines`);
  }
} else {
  out.push("_jscpd output missing._");
}
out.push("");

// --- cycles -----------------------------------------------------------------
out.push("## Import cycles (madge, calibrated to runtime)");
out.push("");
const cycles = read("cycles.txt").trim();
out.push(cycles ? `\`\`\`\n${cycles}\n\`\`\`` : "_cycle output missing._");
out.push("");

// --- dead code --------------------------------------------------------------
out.push("## Dead code (knip)");
out.push("");
const knip = read("knip.txt").trim();
// knip's own build chatter is noise in a summary; keep only its findings.
const knipFindings = knip
  .split("\n")
  .filter(
    (l) => !/^(vite v|transforming|rendering|computing|✓|public\/|$)/.test(l.trim()),
  )
  .join("\n")
  .trim();
out.push(knipFindings ? `\`\`\`\n${knipFindings}\n\`\`\`` : "_clean._");
out.push("");

// --- complexity -------------------------------------------------------------
out.push("## Cognitive complexity (biome, measuring threshold 15)");
out.push("");
let cc = null;
try {
  cc = JSON.parse(read("complexity.json"));
} catch {
  /* absent */
}
if (cc) {
  // metrics.sh distils biome's report to {file, line, score} rows before this
  // runs, dropping the suppression noise the measuring config manufactures.
  const rows = (cc.diagnostics ?? []).map((d) => ({
    file: d.file ?? "?",
    score: Number(d.score ?? 0),
  }));
  const saturated = rows.filter((r) => r.score >= SATURATION);
  const measured = rows.filter((r) => r.score < SATURATION).map((r) => r.score);
  measured.sort((a, b) => a - b);
  const q = (p) => measured[Math.floor(measured.length * p)] ?? 0;

  out.push(`- functions over 15: **${rows.length}**`);
  out.push(`- median ${q(0.5)}, p90 ${q(0.9)}, p95 ${q(0.95)}`);
  out.push(
    `- highest **measurable** score: ${measured.at(-1) ?? 0}` +
      ` (biome saturates at ${SATURATION}; see below)`,
  );
  out.push(
    `- **saturated (score >= ${SATURATION}, true value unknown): ${saturated.length}**`,
  );
  if (saturated.length) {
    out.push("");
    out.push(
      `> Biome's counter saturates at ${SATURATION} — a synthetic function of true` +
        " complexity 300 reports 255. These functions are `>=255`, and their true" +
        ' complexity is **not measured**. Do not read a stable 255 as "no regression".',
    );
    out.push("");
    for (const r of saturated) out.push(`- \`${r.file}\` — >=${SATURATION}`);
  }
  const byFile = new Map();
  for (const r of rows) byFile.set(r.file, (byFile.get(r.file) ?? 0) + 1);
  out.push("");
  out.push("Files with the most over-threshold functions:");
  out.push("");
  for (const [f, n] of [...byFile.entries()].sort((a, b) => b[1] - a[1]).slice(0, 12)) {
    out.push(`- \`${f}\` — ${n}`);
  }
} else {
  out.push("_complexity output missing._");
}
out.push("");

console.log(out.join("\n"));
