/**
 * **Which colours a game shows twice** — the instrument that catches a
 * consolidation collapsing two things a player has to tell apart.
 *
 * `consolidate-colour-palette` replaced ~170 per-game colours with references to
 * a twelve-colour palette, and the failure mode of a pass like that is not a
 * wrong colour, it is *two* right ones landing on the same value. Subsets caught
 * exactly this: its keyboard cursor, its hint's decided slot and its hint's
 * "could still go here" spotlight all resolved to blue, so a three-part
 * deduction the game had deliberately given three colours came out as one.
 *
 * Nothing here can be a pass/fail gate, and it is worth saying why: **most
 * duplicates are correct**. A game paints its givens and its grid in the same
 * ink, its outer and inner background in the same grey, its four error colours
 * in the same red — 170-odd such pairs across the collection, every one of them
 * deliberate. What the report is for is the **diff**: run it before a colour
 * change and after, and a pair that appears is a pair that just collapsed.
 *
 * Run with:
 *
 *     npx vitest run -c scripts/checks/diff.vitest.config.mts colour-collide
 *
 * and read `/tmp/colour-collide.md`. Pairs are named by the game's own `COL_*`
 * constants where those can be recovered, because "subsets 8 vs 11" is not a
 * finding and "subsets COL_CURSOR vs COL_HINT_SPOT" is.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { it } from "vitest";
import { getTsGame } from "../../src/engine/registry.ts";
import type { Colour } from "../../src/engine/types.ts";
import { puzzleIds } from "../../src/puzzle/catalog.ts";
import { colourToOKLCH, isGrayChroma, type OKLCH } from "../../src/utils/color.ts";
import "../../src/games/index.ts";

const OUT = "/tmp/colour-collide.md";

/** The same OKLCH distance the rest of the colour instruments report. */
function distance(a: OKLCH, b: OKLCH): number {
  const ax = isGrayChroma(a[1]) ? 0 : a[1] * Math.cos((a[2] * Math.PI) / 180);
  const ay = isGrayChroma(a[1]) ? 0 : a[1] * Math.sin((a[2] * Math.PI) / 180);
  const bx = isGrayChroma(b[1]) ? 0 : b[1] * Math.cos((b[2] * Math.PI) / 180);
  const by = isGrayChroma(b[1]) ? 0 : b[1] * Math.sin((b[2] * Math.PI) / 180);
  return Math.hypot(a[0] - b[0], ax - bx, ay - by);
}

/** Recover a game's `COL_*` index names from its source, as
 * `colour-inventory.test.ts` does. Only plain integer declarations resolve; a
 * computed one is left unnamed rather than guessed. */
function indexNames(id: string): Map<number, string> {
  const names = new Map<number, string>();
  let files: string[];
  try {
    files = readdirSync(join("src/games", id));
  } catch {
    return names;
  }
  for (const f of files) {
    if (!f.endsWith(".ts") || f.endsWith(".test.ts")) continue;
    const src = readFileSync(join("src/games", id, f), "utf8");
    for (const m of src.matchAll(/^(?:export )?const (COL_[A-Z0-9_]+) = (\d+);/gm))
      if (!names.has(Number(m[2]))) names.set(Number(m[2]), m[1]);
  }
  return names;
}

/** Below this, two entries are the same colour as far as a player is concerned. */
const SAME = 0.02;

it("reports palette entries a game cannot tell apart", () => {
  const lines = [
    "# Colours a game shows twice\n",
    "<!-- Generated by scripts/checks/colour-collide.test.ts. -->\n",
    "Most of these are deliberate — one ink for givens and grid, one red for four",
    "kinds of error. **Read this as a diff against the previous run**: a pair that",
    "newly appears is two meanings that just collapsed into one.\n",
  ];
  let total = 0;
  for (const id of [...puzzleIds].sort()) {
    const game = getTsGame(id);
    if (!game) continue;
    const palette = game.colours([0.827, 0.827, 0.827]);
    const names = indexNames(id);
    const label = (i: number): string => names.get(i) ?? `#${i}`;
    const oklch = palette.map((c: Colour | undefined) => (c ? colourToOKLCH(c) : null));
    const pairs: string[] = [];
    for (let i = 0; i < oklch.length; i++)
      for (let j = i + 1; j < oklch.length; j++) {
        const a = oklch[i];
        const b = oklch[j];
        if (!a || !b || distance(a, b) >= SAME) continue;
        pairs.push(`- \`${label(i)}\` = \`${label(j)}\``);
        total += 1;
      }
    if (pairs.length) lines.push(`### ${id}\n`, ...pairs, "");
  }
  lines.push(`\n**${total} pairs.**\n`);
  writeFileSync(OUT, `${lines.join("\n")}\n`);
  console.log(`wrote ${OUT}: ${total} pairs`);
});
