/**
 * Desc supersession (upstream `midend_supersede_game_desc`) — the engine half
 * of the Mines blocker, driven by a fake game with exactly the shape Mines has:
 * a board whose layout does not exist until the first click, a public desc
 * naming the layout *and* that click, and a private desc naming the layout
 * alone.
 *
 * The fake's layout is a deterministic function of the click, so replaying the
 * move log rebuilds it — as Mines' is, whose generator RNG lives in its state.
 * `textFormat` is the window onto the restored board: it is how each test says
 * *which desc* a restart or a load actually rebuilt from.
 */

import { describe, expect, it } from "vitest";
import type { ChangeNotification } from "../../puzzle/types.ts";
import type { Game } from "./game.ts";
import { Midend } from "./midend.ts";
import { decodeSave } from "./save.ts";

interface MinesishParams {
  size: number;
}
interface MinesishState {
  size: number;
  /** `null` until the first click generates it — the whole point. */
  layout: string | null;
  /** Where the first click landed (the layout is generated around it). */
  clickedAt: number | null;
  opened: number[];
}
type MinesishMove = { click: number };

/** Public desc: `"<click>,<layout>"`. Private desc: `"<layout>"`. Pre-play
 * desc: `"blank"` — no layout at all, which is why it must be superseded. */
const minesish: Game<MinesishParams, MinesishState, MinesishMove, null, null> = {
  id: "__minesish__",
  wantsStatusbar: false,
  isTimed: false,
  canSolve: false,
  canFormatAsText: true,
  defaultParams: () => ({ size: 9 }),
  presets: () => ({ title: "root", params: { size: 9 } }),
  encodeParams: (p) => `s${p.size}`,
  decodeParams: (s) => ({ size: Number(/^s(\d+)$/.exec(s)?.[1] ?? NaN) }),
  validateParams: (p) => (p.size > 0 ? null : "size must be positive"),
  newDesc: () => ({ desc: "blank" }),
  validateDesc: () => null,
  newState: (p, desc) => {
    if (desc === "blank") {
      return { size: p.size, layout: null, clickedAt: null, opened: [] };
    }
    const [head, tail] = desc.split(",");
    // Public desc (click + layout) opens the click; private desc (layout alone)
    // is the same board with nothing opened.
    return tail === undefined
      ? { size: p.size, layout: head, clickedAt: null, opened: [] }
      : { size: p.size, layout: tail, clickedAt: Number(head), opened: [Number(head)] };
  },
  newUi: () => null,
  interpretMove: () => null,
  executeMove: (s, m) => ({
    ...s,
    // The layout is generated by (and around) the first click — deterministic in
    // the click, so replaying the move log rebuilds the same board.
    layout: s.layout ?? `L${m.click}`,
    // Recorded on the first click whether or not the layout was generated
    // *here*: a save restored from the private desc has the layout but not the
    // click, and the replayed click must put it back. (Upstream needs a
    // `set_public_desc` game hook precisely because its `execute_move` records
    // this only while generating — see design.md D3.)
    clickedAt: s.clickedAt ?? m.click,
    opened: [...s.opened, m.click],
  }),
  supersededDesc: (s) =>
    s.layout === null
      ? null
      : { desc: `${s.clickedAt},${s.layout}`, privDesc: s.layout },
  status: () => "ongoing",
  textFormat: (s) =>
    `layout=${s.layout} clicked=${s.clickedAt} opened=[${s.opened.join(",")}]`,
  colours: (bg) => [bg],
  computeSize: () => ({ w: 10, h: 10 }),
};

/** The same game with the hook removed — the guard that a game which says
 * nothing keeps the desc it started with. */
const plain: Game<MinesishParams, MinesishState, MinesishMove, null, null> = {
  ...minesish,
  id: "__plain__",
  supersededDesc: undefined,
};

const BLANK = "layout=null clicked=null opened=[]";

function harness(game = minesish) {
  const notes: ChangeNotification[] = [];
  const m = new Midend(game);
  m.setCallbacks(
    (n) => notes.push(n),
    () => {},
    () => {},
  );
  const gameId = () =>
    [...notes].reverse().find((n) => n.type === "game-id-change")?.currentGameId;
  const idChanges = () => notes.filter((n) => n.type === "game-id-change").length;
  return { m, notes, gameId, idChanges, board: () => m.formatAsText() };
}

describe("desc supersession", () => {
  it("the first click supersedes the desc and re-announces the game ID", () => {
    const h = harness();
    h.m.newGame();
    expect(h.gameId()).toBe("s9:blank");
    expect(h.board()).toBe(BLANK);

    h.m.playMoves([{ click: 4 }]);

    // The shareable ID now names the real board (the layout, and where the
    // click that generated it landed) — not the placeholder the player started
    // from, which describes no layout at all.
    expect(h.gameId()).toBe("s9:4,L4");
    expect(h.idChanges()).toBe(2); // one for the new game, one for the supersession
  });

  it("later moves do not re-announce the ID — the desc is superseded once", () => {
    const h = harness();
    h.m.newGame();
    h.m.playMoves([{ click: 4 }, { click: 7 }, { click: 2 }]);
    expect(h.gameId()).toBe("s9:4,L4");
    expect(h.idChanges()).toBe(2);
  });

  it("undo does not un-supersede: a desc describes the game, not the position", () => {
    const h = harness();
    h.m.newGame();
    h.m.playMoves([{ click: 4 }]);
    h.m.undo();

    // The board is back to blank, but the layout has been generated and the
    // game ID names it. Reverting the desc here would hand out an ID for a
    // board nobody is playing.
    expect(h.board()).toBe(BLANK);
    expect(h.gameId()).toBe("s9:4,L4");
    expect(h.idChanges()).toBe(2);
  });

  it("restart rebuilds from the superseded desc, not the pre-click board", () => {
    const h = harness();
    h.m.newGame();
    h.m.playMoves([{ click: 4 }, { click: 7 }]);
    expect(h.board()).toBe("layout=L4 clicked=4 opened=[4,7]");

    h.m.restartGame();

    // Upstream restarts to *after* the first click, "so you don't have to
    // remember where you clicked": the click is still open and only the second
    // move is gone. Restarting to `history[0]` would have given the blank board.
    expect(h.board()).toBe("layout=L4 clicked=4 opened=[4]");
    expect(h.board()).not.toBe(BLANK);
    // …and nothing is left to undo: the restarted board is the new history[0].
    h.m.undo();
    expect(h.board()).toBe("layout=L4 clicked=4 opened=[4]");
  });

  it("a save taken after supersession carries both descs", () => {
    const h = harness();
    h.m.newGame();
    h.m.playMoves([{ click: 4 }, { click: 7 }]);
    const save = decodeSave(h.m.saveGame());
    expect(save.desc).toBe("4,L4"); // public: layout + first click
    expect(save.privDesc).toBe("L4"); // private: the layout alone
    expect(save.moves).toEqual([{ click: 4 }, { click: 7 }]);
  });

  it("a restored save rebuilds state 0 from the private desc and replays cleanly", () => {
    const h = harness();
    h.m.newGame();
    h.m.playMoves([{ click: 4 }, { click: 7 }]);
    const data = h.m.saveGame();

    const h2 = harness();
    expect(h2.m.loadGame(data)).toBeUndefined();

    // The restored position is the saved one, and the ID still names the real board.
    expect(h2.board()).toBe("layout=L4 clicked=4 opened=[4,7]");
    expect(h2.gameId()).toBe("s9:4,L4");

    // Undo to state 0: it was rebuilt from the *private* desc — the layout with
    // no click. Had it come from the public desc, square 4 would already be
    // open here, and the replayed first click would have opened it twice
    // ("opened=[4,4,7]" at the top of the log).
    h2.m.undo();
    h2.m.undo();
    expect(h2.board()).toBe("layout=L4 clicked=null opened=[]");

    // And the whole thing round-trips again.
    const round = decodeSave(h2.m.saveGame());
    expect(round.desc).toBe("4,L4");
    expect(round.privDesc).toBe("L4");
    expect(round.moves).toEqual([{ click: 4 }, { click: 7 }]);
  });

  it("a save taken before the first click is an ordinary, un-superseded save", () => {
    const h = harness();
    h.m.newGame();
    const save = decodeSave(h.m.saveGame());
    expect(save.desc).toBe("blank");
    expect(save.privDesc).toBeUndefined();

    const h2 = harness();
    expect(h2.m.loadGame(h.m.saveGame())).toBeUndefined();
    expect(h2.gameId()).toBe("s9:blank");
    expect(h2.board()).toBe(BLANK);

    // …and it still supersedes when the click finally comes.
    h2.m.playMoves([{ click: 1 }]);
    expect(h2.gameId()).toBe("s9:1,L1");
  });

  it("a game without the hook never has its desc replaced", () => {
    const h = harness(plain);
    h.m.newGame();
    h.m.playMoves([{ click: 4 }, { click: 7 }]);

    expect(h.gameId()).toBe("s9:blank");
    expect(h.idChanges()).toBe(1);
    expect(decodeSave(h.m.saveGame()).privDesc).toBeUndefined();

    // Restart still returns it to `history[0]` — the rebuild-from-desc branch
    // belongs to superseding games alone.
    h.m.restartGame();
    expect(h.board()).toBe(BLANK);
    expect(decodeSave(h.m.saveGame()).desc).toBe("blank");
  });
});
